### ISSUE TITLE
Finding sound names crashes application

### ISSUE THREAD

**Issue by ondrowan** [stephenfournier/Dota-2-ModKit#49]
> ex.toString(): System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'git2-4d6362b': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at LibGit2Sharp.Core.NativeMethods.git_libgit2_init()
   at LibGit2Sharp.Core.NativeMethods.LibraryLifetimeObject..ctor()
   at LibGit2Sharp.Core.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at LibGit2Sharp.Core.NativeMethods.RemoveHandle()
   at LibGit2Sharp.Core.NativeMethods.LibraryLifetimeObject.Finalize()
InnerException.toString(): System.DllNotFoundException: Unable to load DLL 'git2-4d6362b': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at LibGit2Sharp.Core.NativeMethods.git_libgit2_init()
   at LibGit2Sharp.Core.NativeMethods.LibraryLifetimeObject..ctor()
   at LibGit2Sharp.Core.NativeMethods..cctor()

Tried it on Windows 10 only.

`vsnd_to_soundname_v2.txt` was created successfully before it crashed.

**Comment by stephenfournier** [comment]
Do you have NativeBinaries\x86\git2-4d6362b.dll in the same directory as D2ModKit.exe?

**Comment by ondrowan** [comment]
Today's update fixed it for me it seems. Not sure what was the problem before. I've updated from some older version (few months old probably) by replacing the exe file and it didn't autodownload the dll file.
